name: scrapegis
version: "0.1.0"

dependencies:
 - base
 - lens 
 - mtl
 - aeson >= 0.11.0.0
 - wreq
 - docopt
 - cassava
 - bytestring
 - containers
 - text
 - vector
 - docopt

library:
  source-dirs: src

executables:
  scrapegis:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -Wall
    dependencies:
    - scrapegis


tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fwarn-tabs
      - -O0
    dependencies:
    - scrapegis
    - hspec
